- name: Build generic C project
  hosts: local
  become: false

  vars:
    project_path: ""

  tasks:
    - name: Install dependencies
      become: true
      apt:
        name: build-essential
        state: present
        update_cache: yes

    - name: Build project
      command: make
      args:
        chdir: "{{ playbook_dir }}/../{{ project_path }}"
