name: C Project CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible playbook
        run: |
          ansible-playbook -i ansible/inventory ansible/playbook.yml

      - name: Test executable
        run: |
          ./build/bin/app